# Generated by Django 3.1.2 on 2021-01-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=100)),
                ('voter_id', models.CharField(max_length=100)),
            ],
        ),
    ]
